import { useNavigate } from 'react-router-dom';
import { ArrowRight, Award, BookOpen, CalendarClock, CheckCircle2, Clock3, Flame, Play, Sparkles, Target, Zap } from 'lucide-react';
import { assignments, courses } from '../../data/mock';
import { Badge, Button, Card, CourseCard, Progress, SectionTitle, StatCard } from '../../components/ui';
import hero from '../../assets/industrial-skills-hero.png';

export function StudentDashboard(){const navigate=useNavigate();return <div className="dashboard-page">
 <div className="welcome-line"><div><span className="eyebrow">THURSDAY, AUGUST 13</span><h1>Good evening, Amit <span>👋</span></h1><p>Your workshop practical is scheduled for today at 4:30 PM.</p></div><div className="streak-pill"><Flame/><span><b>12 safe sessions</b><small>Personal best: 18</small></span></div></div>
 <section className="continue-hero"><img src={hero} alt="Industrial skills training workshop"/><div className="hero-shade"/><div className="continue-copy"><Badge tone="glass"><Zap size={12}/> NEXT PRACTICAL</Badge><p>Industrial Electrician</p><h2>Three-Phase Motor Starters</h2><span>Module 2 · Practical 3 · 32 min</span><div className="hero-progress"><Progress value={62}/><b>62%</b></div><Button onClick={()=>navigate('/student/courses/industrial-electrician/learn/state')}><Play size={17} fill="currentColor"/> Continue training</Button></div><div className="hero-orbit"><Sparkles/><span>+40 skill pts</span></div></section>
 <div className="stat-grid student-stats"><StatCard label="Training hours" value="184h" detail="↑ 12h this month" icon={<Clock3/>}/><StatCard label="Practicals complete" value="27" detail="3 this week" icon={<CheckCircle2/>}/><StatCard label="Skill points" value="2,840" detail="82% job-ready" icon={<Zap/>}/><StatCard label="Credentials" value="4" detail="1 earned recently" icon={<Award/>}/></div>
 <div className="content-split"><div><SectionTitle title="My learning" subtitle="Pick up right where you left off" action={<button className="text-button" onClick={()=>navigate('/student/learning')}>View all <ArrowRight/></button>}/><div className="course-row">{courses.filter(c=>c.progress>0&&c.progress<100).slice(0,3).map(c=><CourseCard key={c.id} course={c} onOpen={()=>navigate(`/student/courses/${c.id}`)}/>)}</div></div><Card className="upcoming-panel"><SectionTitle title="Coming up" action={<button className="icon-link" onClick={()=>navigate('/student/calendar')}><CalendarClock/></button>}/><div className="timeline">{assignments.slice(0,3).map((a,i)=><button key={a.id} onClick={()=>navigate(`/student/assignments/${a.id}`)}><time><b>{i===0?'TODAY':i===1?'SAT':'MON'}</b><span>{13+i*3}</span></time><i/><div><Badge tone={i===0?'danger':'neutral'}>{i===0?'Due today':a.course.split(' ')[0]}</Badge><h4>{a.title}</h4><p>{a.due}</p></div></button>)}</div></Card></div>
 <div className="content-split lower"><Card className="skills-card"><SectionTitle title="Trade skills in progress" subtitle="Evidence from theory and workshop assessments" action={<button className="text-button" onClick={()=>navigate('/student/skills')}>View skills passport <ArrowRight/></button>}/>{[['Electrical Safety',92,'Competent'],['Motor Control',72,'Practicing'],['Fault Diagnosis',48,'Developing']].map(([name,val,lvl])=><div className="skill-progress" key={String(name)}><div className="skill-icon">{String(name).slice(0,1)}</div><div><span><b>{name}</b><small>{lvl}</small></span><Progress value={Number(val)} small/></div><strong>{val}%</strong></div>)}</Card><Card className="recommend-card"><div><Badge tone="violet"><Sparkles size={12}/> NEXT course</Badge><h3>HEMM Mechanic</h3><p>Recommended because your electrical and diagnostics foundation transfers well.</p><button onClick={()=>navigate('/student/courses/hemm-mechanic')}>View course <ArrowRight/></button></div><div className="recommend-orb"><Target/></div></Card></div>
 </div>}
