import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { Check, ChevronRight, Clock3, Star } from 'lucide-react';
import type { Course } from '../types';

export function Button({className='',variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button className={`btn btn-${variant} ${className}`} {...props}/>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>}
export function Progress({value,small=false}:{value:number;small?:boolean}){return <div className={`progress ${small?'progress-sm':''}`} role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${Math.min(value,100)}%`}}/></div>}
export function Avatar({name,size='md'}:{name:string;size?:'sm'|'md'|'lg'}){return <span className={`avatar avatar-${size}`} aria-label={name}>{name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="head-actions">{actions}</div>}</header>}
export function StatCard({label,value,detail,icon}:{label:string;value:string;detail:string;icon?:ReactNode}){return <div className="stat-card"><div className="stat-top"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{detail}</small></div>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function EmptyState({icon,title,body,action}:{icon:ReactNode;title:string;body:string;action?:ReactNode}){return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{body}</p>{action}</div>}
export function CourseCard({course,onOpen,compact=false}:{course:Course;onOpen:()=>void;compact?:boolean}){return <article className={`course-card ${compact?'course-compact':''}`} onClick={onOpen} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&onOpen()}><div className={`course-art art-${course.color}`}><div className="course-glyph">{course.skills[0].slice(0,2)}</div><Badge tone="glass">{course.category}</Badge></div><div className="course-body"><div className="course-meta"><span><Star size={13} fill="currentColor"/> {course.rating}</span><span>{course.level}</span></div><h3>{course.title}</h3><p>{course.instructor}</p>{course.progress>0&&<><div className="progress-label"><span>{course.next}</span><b>{course.progress}%</b></div><Progress value={course.progress} small/></>} {!course.progress&&<div className="course-footer"><span><Clock3 size={14}/>{course.duration}</span><span>{course.lessons} lessons</span></div>}</div></article>}
export function SectionTitle({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <div className="section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
export function StatusBadge({status}:{status:string}){const tone=status==='Active'||status==='Published'||status==='Graded'||status==='Completed'?'success':status==='At risk'||status==='Overdue'?'danger':status==='Draft'?'neutral':'warning';return <Badge tone={tone}>{status}</Badge>}
export function CheckItem({children,done=true}:{children:ReactNode;done?:boolean}){return <div className="check-item"><span className={done?'done':''}>{done?<Check size={14}/>:<ChevronRight size={14}/>}</span>{children}</div>}
export function Skeleton({height=120}:{height?:number}){return <div className="skeleton" style={{height}}/>}
