import { useEffect, useState, type MouseEvent as ReactMouseEvent } from 'react';
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { Award, BarChart3, Bell, BookCopy, BookOpen, Bot, BriefcaseBusiness, Building2, CalendarDays, CheckSquare, ChevronDown, CircleHelp, Compass, FileBarChart, FolderOpen, GraduationCap, Home, LayoutDashboard, Library, LogOut, Menu, MessageCircle, Moon, Network, PanelLeftClose, PanelLeftOpen, Search, Settings, ShieldCheck, Sparkles, Sun, Trophy, UserRound, Users, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import type { Role } from '../types';
import { Avatar, Badge, Button } from '../components/ui';
import { ToastLayer } from '../components/ToastLayer';

const iconMap:Record<string,LucideIcon>={Home,BookOpen,Compass,Network,CalendarDays,CheckSquare,MessageCircle,Trophy,Award,LayoutDashboard,BookCopy,Users,BarChart3,GraduationCap,Building2,FolderOpen,FileBarChart,Settings,ShieldCheck,BriefcaseBusiness,Library};
const nav:Record<Role,{label:string,path:string,icon:string}[]>={
 student:[['Home','/student','Home'],['My Training','/student/learning','BookOpen'],['Courses','/student/explore','Compass'],['Career Pathways','/student/paths','Network'],['Skills Passport','/student/skills','Sparkles'],['Training Calendar','/student/calendar','CalendarDays'],['Practicals','/student/assignments','CheckSquare'],['Trade Community','/student/discussions','MessageCircle'],['Badges','/student/achievements','Trophy'],['Credentials','/student/certificates','Award']].map(([label,path,icon])=>({label,path,icon})),
 teacher:[['Dashboard','/teacher','LayoutDashboard'],['Courses','/teacher/courses','BookCopy'],['Course Builder','/teacher/courses/new','BriefcaseBusiness'],['Trainees','/teacher/students','Users'],['Practicals','/teacher/assignments','CheckSquare'],['Assessments','/teacher/quizzes','GraduationCap'],['Competency Book','/teacher/gradebook','FileBarChart'],['Trade Community','/teacher/discussions','MessageCircle'],['Batch Calendar','/teacher/calendar','CalendarDays'],['Training Analytics','/teacher/analytics','BarChart3']].map(([label,path,icon])=>({label,path,icon})),
 admin:[['Overview','/admin','LayoutDashboard'],['Trainees','/admin/users','Users'],['Courses','/admin/courses','BookCopy'],['Career Pathways','/admin/learning-paths','Network'],['Skill Framework','/admin/skills','Sparkles'],['Trainers','/admin/instructors','GraduationCap'],['Centers & Batches','/admin/groups','Building2'],['Enrollments','/admin/enrollments','CheckSquare'],['Reports','/admin/reports','FileBarChart'],['Analytics','/admin/analytics','BarChart3'],['Credentials','/admin/certificates','Award'],['Training Resources','/admin/content','Library'],['Announcements','/admin/announcements','Bell'],['Audit Logs','/admin/audit-log','ShieldCheck'],['Institute Settings','/admin/settings','Settings']].map(([label,path,icon])=>({label,path,icon})),
};
const identities={student:{name:'Amit Kumar',detail:'Industrial Electrician trainee'},teacher:{name:'Rajesh Kumar',detail:'Senior Electrical Trainer'},admin:{name:'Neha Verma',detail:'Institute Administrator'}};

export function AppShell(){const {role,logout,theme,toggleTheme,sidebar,toggleSidebar,notifications,markAllRead,commandOpen,setCommandOpen,addToast}=useAppStore();const [mobile,setMobile]=useState(false);const [noticeOpen,setNoticeOpen]=useState(false);const [profileOpen,setProfileOpen]=useState(false);const navigate=useNavigate();const location=useLocation();
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#080b12':'#f5f3fa')},[theme]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommandOpen(true)}if(e.key==='Escape')setCommandOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[setCommandOpen]);
 const signOut=()=>{logout();navigate('/login',{replace:true})};
 const commandItems=role==='student'?[{label:'Continue motor starter practical',path:'/student/courses/industrial-electrician/learn/state',icon:BookOpen},{label:'Explore courses',path:'/student/explore',icon:Compass},{label:'Open skills passport',path:'/student/skills',icon:Sparkles}]:role==='teacher'?[{label:'Open course builder',path:'/teacher/courses/new',icon:BriefcaseBusiness},{label:'Review practical assessments',path:'/teacher/grading/a1',icon:CheckSquare},{label:'View training analytics',path:'/teacher/analytics',icon:BarChart3}]:[{label:'Manage trainees',path:'/admin/users',icon:Users},{label:'Review course catalog',path:'/admin/courses',icon:BookCopy},{label:'Open institute analytics',path:'/admin/analytics',icon:BarChart3}];
 const handleWorkspaceAction=(event:ReactMouseEvent<HTMLDivElement>)=>{const button=(event.target as HTMLElement).closest('button');if(!button||button.dataset.handled==='true')return;const label=(button.textContent||'').replace(/\s+/g,' ').trim();if(!label&&(button.closest('.course-manage-row')||button.closest('.generic-row')||button.closest('.table-row'))){addToast('Action menu opened');return}if(button.closest('.filter-tabs')&&!['All','Due soon','Submitted','Graded','Overdue'].includes(label.replace(/\d+/g,'').trim())){button.parentElement?.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');addToast(`${label.replace(/\d+/g,'').trim()} filter applied`);return}const routes:Record<string,string>={
  'Create course':'/teacher/courses/new',...(role==='teacher'?{'View all':'/teacher/students'}:{}),'View all →':role==='admin'?'/admin/users':'/teacher/students','Add learner':'/admin/users','View all 142':'/admin/users','Open learner →':'/admin/users','Review →':'/admin/users','View learning plan':'/student/paths','Join the conversation →':'/student/discussions','New post':'/student/discussions','Edit profile':'/student/profile','View lesson':'/teacher/courses','Explore signal':'/admin/analytics'
 };if(routes[label]){navigate(routes[label]);return}if(label==='Export'||label==='Export CSV'){const csv='Name,Status,Progress\nAarav Sharma,Active,78%\nMaya Chen,Active,92%';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=`${role}-workspace-export.csv`;link.click();URL.revokeObjectURL(url);addToast('Export downloaded','success');return}if(label==='Download'){const url=URL.createObjectURL(new Blob(['Pantiss Skill Universe demo resource'],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='pantiss-resource.txt';link.click();URL.revokeObjectURL(url);addToast('Download ready','success');return}if(label.includes('Share')){navigator.clipboard?.writeText(window.location.href);addToast('Share link copied','success');return}if(['All courses','All statuses','All departments','All roles','Filters','Last 6 months','Recommended'].some(x=>label.startsWith(x))){addToast(`${label} options opened`);return}if(label==='Manage'||label==='Review'||label.startsWith('Create ')){addToast(`${label} panel opened`);return}const feedback=['Ask Skill Universe','Ask analytics','Generate suggestions','Preview','Keyboard shortcuts','Attach file','Add a link','Flag for review','CC','1×','Needs work','Good','Excellent','Edit submission'];if(feedback.includes(label))addToast(label==='1×'?'Playback speed changed':`${label} opened`,'info')};
 return <div className={`app-shell ${sidebar?'':'sidebar-collapsed'}`} onClick={handleWorkspaceAction}>
  <aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand"><span className="brand-mark"><Sparkles size={19}/></span>{sidebar&&<div><strong>Pantiss</strong><small>Industrial Skills</small></div>}<button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div>
   <nav aria-label={`${role} navigation`}>{nav[role].map(item=>{const Icon=iconMap[item.icon]||Sparkles;return <NavLink key={item.path} to={item.path} end={item.path===`/${role}`} onClick={()=>setMobile(false)} title={!sidebar?item.label:undefined}><Icon size={19}/>{sidebar&&<span>{item.label}</span>}</NavLink>})}</nav>
   <div className="sidebar-foot"><div className="sidebar-identity"><Avatar name={identities[role].name} size="sm"/>{sidebar&&<span><b>{identities[role].name}</b><small>{role[0].toUpperCase()+role.slice(1)} workspace</small></span>}<button onClick={signOut} aria-label="Sign out" title="Sign out"><LogOut/></button></div>{sidebar&&<button className="help-row" onClick={()=>setCommandOpen(true)}><CircleHelp size={18}/><span>Help & shortcuts</span></button>}</div>
  </aside>
  <div className="workspace"><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><button className="collapse-button" onClick={toggleSidebar} aria-label="Toggle sidebar">{sidebar?<PanelLeftClose/>:<PanelLeftOpen/>}</button><button className="global-search" onClick={()=>setCommandOpen(true)}><Search size={17}/><span>Search courses, skills, people…</span><kbd>⌘ K</kbd></button></div><div className="top-actions"><button onClick={toggleTheme} aria-label="Toggle theme">{theme==='light'?<Moon/>:<Sun/>}</button><button className="ai-quick" onClick={()=>{setCommandOpen(true)}}><Bot/><span>Ask AI</span></button><div className="notice-wrap"><button onClick={()=>setNoticeOpen(!noticeOpen)} aria-label="Notifications"><Bell/><i>{notifications.filter(n=>!n.read).length}</i></button>{noticeOpen&&<div className="notification-pop"><div className="pop-head"><h3>Notifications</h3><button onClick={markAllRead}>Mark all read</button></div>{notifications.map(n=><div className={`notification ${n.read?'':'unread'}`} key={n.id}><span/><div><b>{n.title}</b><p>{n.detail}</p><small>{n.time}</small></div></div>)}</div>}</div><div className="profile-wrap"><button className="profile-button" onClick={()=>setProfileOpen(v=>!v)} aria-expanded={profileOpen}><Avatar name={identities[role].name} size="sm"/><div><b>{identities[role].name}</b><small>{identities[role].detail}</small></div><ChevronDown size={15}/></button>{profileOpen&&<div className="profile-menu"><div><Avatar name={identities[role].name}/><span><b>{identities[role].name}</b><small>{role[0].toUpperCase()+role.slice(1)} account</small></span></div><button onClick={signOut}><LogOut/><span>Sign out</span></button></div>}</div></div></header>
   <main className="page"><Outlet/></main>
  </div>
  {commandOpen&&<div className="command-backdrop" onMouseDown={()=>setCommandOpen(false)}><div className="command" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><div className="command-input"><Search/><input autoFocus placeholder={`Search the ${role} workspace…`}/><kbd>ESC</kbd></div><div className="command-content"><small>QUICK ACTIONS</small>{commandItems.map(x=><button key={x.label} onClick={()=>{navigate(x.path);setCommandOpen(false)}}><x.icon/><span>{x.label}</span><ChevronDown className="command-arrow"/></button>)}<small>CURRENT WORKSPACE</small><div className="recent-chips"><Badge tone="violet">{role[0].toUpperCase()+role.slice(1)}</Badge><Badge>{location.pathname}</Badge></div></div></div></div>}
  <ToastLayer/>
 </div>;
}
